POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9sYWp1d25zaW5jbGFpcjRAZ21haWwuY29tIiwiZXhwIjoxNzU2NjU1MzI3LCJ1c2VySWQiOjJ9._vzOIHHipuvOSA1WLLevJtY7194s4C8eaOBCO-TFRiY

{
    "name":"Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}